### ISSUE TITLE
Plugin logs out all the time

### ISSUE THREAD

**Issue by anareaty** [fleetingnotes/fleeting-notes-obsidian#120]
Plugin periodically logs out. Sometimes after several days, sometimes several times in one day. I think login credentials should be somehow stored locally, so we don't need to type it in every time.

**Comment by matthewwong525** [comment]
I'll look into this. The solution may just be updating the supabase package and handling logouts more elegantly

**Comment by matthewwong525** [comment]
See https://github.com/fleetingnotes/fleeting-notes-flutter/blob/5ab9318f478f7e250f95ba59c1499ba5f2bdd3c1/lib/screens/main/main_screen.dart#L83
