### ISSUE TITLE
Syncing Issue Between Fleeting Notes and Obsidian

### ISSUE THREAD

**Issue by gonzalovelasco** [fleetingnotes/fleeting-notes-obsidian#124]
When editing a note in Fleeting Notes without a title and then adding a title, it fails to update the corresponding note in Obsidian and create a new one.

**To Reproduce**
-Open Fleeting Notes.
-Create a new note without a title but with content.
-Observe the sync with Obsidian.
-Update the new note in Fleeting Notes adding a title.

**Expected behavior**
The note in Fleeting Notes should sync with Obsidian and update the note with appropriate content and a title in Obsidian.

**Actual behavior** 
The update of the note is creating a new note with the title in Obsidian

**Comment by matthewwong525** [comment]
Let's close it and see if it comes up in the future. may have been fixed by a previous PR
