### ISSUE TITLE
Dateformat

### ISSUE THREAD

**Issue by kirso** [fleetingnotes/fleeting-notes-obsidian#16]
Is there a way to adjust the date format to pure YYYY-MM-DD type?

**Comment by matthewwong525** [comment]
I don't think there's a way to do that now. That being said, templater commands work according to a user from the [discord](https://discord.gg/xrj6yuGNmx) (e.g. `<% tp.date.now("M" ) %>`). Not sure if that's helpful but maybe you can do something with that.

Anyways, I'll look into adding a solution for this.

**Comment by matthewwong525** [comment]
#19 will solve this
