### ISSUE TITLE
[Feature Request] tags metadata 

### ISSUE THREAD

**Issue by NaturallyAsh** [fleetingnotes/fleeting-notes-obsidian#29]
Hello. Great app and plugin by the way! 

Is it possible for you to add "tags" field to the app? I always place my tags in the frontmatter of my Obsidian note because I use a plugin that automatically moves my notes between folders based on tags.

Many thanks for your hard work, and looking forward to seeing this app and plugin grow!

**Comment by matthewwong525** [comment]
Hello! did you try adjusting the note metadata in the plugin settings? In there you can manually adjust the metadata to include tags you'd like.

Let me know if that helps!

**Comment by NaturallyAsh** [comment]
That works for a tag that I want all my notes to include. But I was thinking more about having tags as a field option. So, in the app, I could type a tag or tags in a box under the title section or something, and FN would grab that tag during the sync. Because I might have a tag in mind when I'm creating the FN and would want to quickly insert it along with my note in the app. Otherwise, I'll have to manually add a different tag every time to the template. That wouldn't be very practical and I wouldn't be able to automate my incoming FN. Hope I'm making sense, lol. 

I'm excited to use FN, but the tags predicament is the only thing holding me back right now.

**Comment by matthewwong525** [comment]
Interesting, I'll look into implementing this feature. thanks again for the suggestion. i'm assuming you want an array of tags like: `[ "hello", "world"]`.

**Comment by NaturallyAsh** [comment]
Yes please, that would be perfect!

**Comment by matthewwong525** [comment]
@ransurf use the following regex to find hashtags [source](https://stackoverflow.com/questions/42065872/regex-for-a-valid-hashtag)
```
(^|\B)#(?![0-9_]+\b)([a-zA-Z0-9_]{1,30})(\b|\r)
```
