### ISSUE TITLE
No need to “turn off safe mode.”

### ISSUE THREAD

**Issue by EricEWeir** [fleetingnotes/fleeting-notes-obsidian#35]
“Safe mode” is now “restricted mode” and it is off by default. Telling people, at least newbies like me, to “turn safe mode off” is confusing. 

And a bit intimidating: “Is ‘restricted mode’ ‘safe mode’? Is ‘on’ ‘off’? Is my vault going to be obliterated if I guess wrong?”

**Comment by matthewwong525** [comment]
Thanks for bringing this up, i'll be updating the documentation
