### ISSUE TITLE
Handling deleted notes in obsidian

### ISSUE THREAD

**Issue by iroQuai** [fleetingnotes/fleeting-notes-obsidian#4]
I love two way sync! I think it could be enhanced by better handling deleted notes in obsidian. At this point (v0.2.1) the note just gets added again in obsidian after next sync. I'd prefer that the note would get deleted in the fleeting notes app too!

I realise this could create problematic situations where ones notes all get deleted by accident when the sync plugin isn't set up properly.  Maybe a "trash" folder could help avoid this?

**Comment by matthewwong525** [comment]
Hey @iroQuai thank you for the feedback! I'd like to understand your use case for this. Do you want to delete the Fleeting Notes after it's been synced with Obsidian?

I'm asking because I've gotten feedback from other people who want a feature to delete the note from Fleeting Notes after it's been synced to Obsidian. I'm wondering if you fit in this same group as well.

**Comment by iroQuai** [comment]
Actually I do not really delete the note, but most of the time I edit the note to a more permanent form and move the note to a different folder (probably the main vault folder, sometimes the "sources" folder if the note mainly contains highlights from an URL)

So after I processed the fleeting note in obsidian and moved it to a more permanent spot, I'd like the the note to be gone in the fleeting notes app too!

**Comment by matthewwong525** [comment]
It sounds like you "process" your notes once you take them. I've added a command to make it easier to grab unprocessed notes. here is a video of it in action: https://www.youtube.com/watch?v=sFQaDeFNecc

Let me know if this is helpful for you! @iroQuai

**Comment by iroQuai** [comment]
I really appreciate you working on a solution!I tried working with it but I find this solution pretty unnatural. Isn't there a way to change some metadata or add a checkmark to a note? I'd rather mark a specific note as processed than a central list with checkmarks...

**Comment by matthewwong525** [comment]
thanks for the suggestion, i'll be adding an option to delete notes in the metadata in the near future! see #13 for more updates
