### ISSUE TITLE
Struggling with syncing to Onsidian

### ISSUE THREAD

**Issue by EricEWeir** [fleetingnotes/fleeting-notes-obsidian#40]
I’ve got a small collection of notes in the Fleeting Notes app. I’ve specified the obsidian location for my fleeting notes. When I run the “Insert unprocessed notes” command I get “Failed to insert unprocessed notes.”

**Comment by matthewwong525** [comment]
Hey Eric, just saw this message on github now, the solution (answered via email) to this was to run the "Sync Fleeting Notes" command instead. The wording is quite misleading (because it implies that notes from Obsidian are pushed to Fleeting Notes app) and we are considering changing it..
