### ISSUE TITLE
Cannot create a new account! frozen loading icon

### ISSUE THREAD

**Issue by tecnoborder** [fleetingnotes/fleeting-notes-obsidian#49]
Hello there,
when I try to create an account either from the app or online, I got stuck at the circling loading icon, but nothing happens

**Comment by matthewwong525** [comment]
Hey! Adriano, please send me your email and I can help you from there to (ithinkwong@gmail.com). Otherwise, try logging in rather than registering as you may have already registered with that email. If you forgot your password, click the "Trouble signing in" button.

**Comment by matthewwong525** [comment]
Also thank you for reporting this, I'm looking to fix this in the next release with more verbose error messages and not have a stuck loading screen.

**Comment by matthewwong525** [comment]
This problem should be fixed with 0.6.9 version of the Fleeting Notes app
