### ISSUE TITLE
Feature request: Autopopulate note title with web page title

### ISSUE THREAD

**Issue by nikultcev** [fleetingnotes/fleeting-notes-obsidian#59]
Is it possible to add an option to Android version to autopopulate a note title with source name when i highlight a passage in a web page and share it to Fleeting notes?

**Comment by matthewwong525** [comment]
On android you'll need to "Share highlight" instead of normally just sharing the text. This'll also share the link to Fleeting Notes. See how you can do it here. Let me know if that helps!

https://support.google.com/chrome/answer/10256233?hl=en&co=GENIE.Platform%3DAndroid
