### ISSUE TITLE
Enable notes from our synced obsidian vault to come up as suggestions on the fleeting notes app when using the [[ and typing the first few letters on android

### ISSUE THREAD

**Issue by sharetocreate** [fleetingnotes/fleeting-notes-obsidian#62]
**Is your feature request related to a problem? Please describe.**
My android phone syncs my vault to my android. I use fleeting notes to capture so can’t see the relevance of linking notes together in the app itself

**Describe the solution you'd like**
Is there any way of getting the notes from obsidian vault to come up as suggestions on the app when using the [[ and typing the first few letters? Like using the search query to find any other reference to a note before creating a new note so we can much more effectively build our zettelkasten

**Describe alternatives you've considered**
Create a new note in Fleeting Notes and add [[links]] that are within your vault to that note. - too cumbersome when adding links / new notes all the time in obsidian

**Comment by matthewwong525** [comment]
This is a fantastic feature but I'll need to think of a way to seamlessly integrate this. I'm very much leaning towards creating a fleeting note from within the Obsidian plugin with all the links within it. If you do have one-way + delete enabled it should not ignore this note with a title specified by you.

**Comment by sharetocreate** [comment]
Thanks matt

**Comment by sharetocreate** [comment]
Ahh wow - did you find a way to implement this Matt?

**Comment by matthewwong525** [comment]
Yep @sharetocreate ! you can try it out now! it's released on version v0.5.2. SImply go to the settings and enable "Sync Obsidian [[links]] to Fleeting Notes"
<img width="547" alt="image" src="https://user-images.githubusercontent.com/20890995/216473720-039316a5-8980-488e-984e-0ae776e53064.png">

**Comment by sharetocreate** [comment]
Amazing - well done mate - will try in a bit

**Comment by sharetocreate** [comment]
Sorry but how to update? Not seeing the feature & play store comes up with
cant install fleeing notes, when clicking on update

I normally click on the updates via email, but would be great if app could
update automatically with the rest if poss. Looking forward to try out the
links feature - best. Marc

**Comment by matthewwong525** [comment]
@sharetocreate you'll need to install the Fleeting Notes Sync plugin from within Obsidian. The community plugin performs the syncs the links from within Obsidian. So it's not something within the Fleeting Notes app. Hopefully this helps.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20890995/216631173-cfa84907-71b1-49cf-a3f0-79d7fa03d0c4.png">

**Comment by sharetocreate** [comment]
Ah i see. Thanks Matt. Updated. Is there any other steps? I have one way
sync but dont see a note created with any links in either obsidian or
fleeting notes anddroid app so think im missing something.

**Comment by sharetocreate** [comment]
Emailed also via my account email so can disregard this thread to save
duplicating :)

**Comment by matthewwong525** [comment]
Just to update people reading this thread. The problem was resolved by logging in and out within the Obsidian plugin.
