### ISSUE TITLE
Expose source metadata to Obsidian plugin from Fleeting Notes

### ISSUE THREAD

**Issue by formlessdao** [fleetingnotes/fleeting-notes-obsidian#63]
Hi. 
First thank you for creating a Firefox extension that can capture info into Obsidian. There's pretty much only one other Firefox extension that works with Obsidian, and is not really great.
When I right click a video on youtube I want when I click "Save Link" the addon to extract all essential info about the video that I need:
-I need the title of the video
-The thumbnail that the content creator uses for that video.
-The duration of the video.
-The channel name that that video is part of.
-The full youtube description for that video.

Would you be willing please to make your addon extract all these bits of info about the video so I can save them into Obsidian?

**Comment by matthewwong525** [comment]
Thank you for the feature request!

Note to self: perhaps have the source metadata stored within supabase and expose it as a ${variable} in the Fleeting Notes Obsidian plugin.
