### ISSUE TITLE
New notes created in Obsidian should show up in Fleeting Notes web app

### ISSUE THREAD

**Issue by shanteshpatil** [fleetingnotes/fleeting-notes-obsidian#65]
- Currently new notes created in Obsidian in the Fleeting Notes folder don't show up in the Fleeting Notes web app
- Only notes created in web app show up in the Obsidian list.
- Also notes synced from Fleeting Notes to Obsidian when deleted from Obsidian should also reflect the same in the Fleeting Notes web app

**Comment by matthewwong525** [comment]
Thanks for the feature request!
