### ISSUE TITLE
Optional sync of deletion of Fleeting notes to Obsidian

### ISSUE THREAD

**Issue by papadage** [fleetingnotes/fleeting-notes-obsidian#68]
I use Fleeting Notes as a way of putting quick reminders and ideas into my Weekly Note in Obsidian in combination with the Periodic Notes plugin and dataview. As I either create full files to act on each item, or address them, they become clutter in the note. I don't use tasks in Fleeting Notes since it slows down data entry with the added needed formatting.

I would like to have the ability to delete the note in any manner (Chrome plugin, phone app, or delete in Obsidian) and have that sync across all devices. 

Alternatively, a way to mark them as Archived so they don't show that can be queried by dataview would work just as well. I don't care about the file system clutter as I can keep the FleetingNotesApp folder collapsed. But a metadata field in the frontmatter for archive would allow me to automatically filter out acted upon items. Another idea is to have an option to make every entry a task so they can be checked off and filtered out.

Here is the context.. a long flat list of notes. Since I use Fleeting Notes for frictionless adding items, I don't want to take the time to prepend keywords to use for sorting and grouping. So all I get is a flat, disorganized list.

![image](https://user-images.githubusercontent.com/28878971/218123115-8619075d-6a7d-4206-aa3c-95b92ca558da.png)

**Comment by matthewwong525** [comment]
Thanks for the feature request! just going to add a screenshot of your reddit comment for some ideas:
![image](https://user-images.githubusercontent.com/20890995/218182192-ce38c346-e610-435c-b4f4-fdce5b4bf7bb.png)

**Comment by matthewwong525** [comment]
Regarding your third point I think it may be related to https://github.com/fleetingnotes/fleeting-notes-flutter/issues/447. Basically to make it easier to add TODOs through a toolbar

**Comment by papadage** [comment]
That’s great. One issue, though. I have deleted your first notes with the advice/hints and some of my test notes. They have already been deleted in the app, but they keep coming back, so they are in my current weekly note as well.

Regards,

George Papadakis

**Comment by matthewwong525** [comment]
@papadage this seems like a seperate bug. Could you file a bug report for this so I can get all the info I need to work on it!?Thanks again :) 

https://github.com/fleetingnotes/fleeting-notes-flutter/issues/new/choose
