### ISSUE TITLE
FR: Plugin should download attachments when synching

### ISSUE THREAD

**Issue by spiritualgeek** [fleetingnotes/fleeting-notes-obsidian#74]
**Is your feature request related to a problem? Please describe.**
Presently, images or attachments generate an .md file with a link similar to `https://yixxxxxxxxxxxxxxxxx.supabase.co/storage/v1/object/public/attachments/6xxxxxxx-bxxx-xxxx-xxxx-xxxxxxxxxxxx/file.png` which is fine I suppose, but when synching to obsidian the file should come across and not just remain as a link. Presently one is, kind of, downloading at attachment twice.

**Describe the solution you'd like**
When synching, it must download all attachments (images, pdf and anything else) in the same folder that the fleeting notes plugin is set to use. If the user has an assets folder defined in Obsidian, it would place the attachments there.

**Describe alternatives you've considered**
https://github.com/fleetingnotes/fleeting-notes-obsidian/issues/new/choose was proposed.
With this plugin, I would need to do it page by page, which is tedious. I would not let it loose on my entire vault, as I don't want links to images downloaded across the board.

**Additional context**
N/A

**Comment by matthewwong525** [comment]
thanks for putting in this feature request :)

**Comment by spiritualgeek** [comment]
Any idea whether you will implement this, as it's really starting to get frustrating? :)

**Comment by matthewwong525** [comment]
Im so sorry for the inconvenience! I've been working on pushing through the door some other features but this will be a priority this coming week. To give you an estimate probably in a week or so. Here's my roadmap if you're curious: https://github.com/orgs/fleetingnotes/projects/1/views/4
